#dataSource:
#    pooled: true
#    jmxExport: true
#    driverClassName: com.mysql.jdbc.Driver
#    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    username: root
#    password: admin
#
#environments:
#    development:
#        dataSource:
#            dbCreate: update
#            url: jdbc:mysql://localhost:3306/testDB